language: haxe

install:
  - yes | haxelib install test.hxml
  - yes | haxelib install app.hxml

script:
  - haxe hxml/test.js.hxml
  - haxe hxml/test-neko.hxml
  - neko out/neko/test.n
  - haxe hxml/app.neko.hxml
