language: haxe

install:
  - yes | haxelib install test.hxml
  - yes | haxelib install app.hxml
  - yes | haxelib install hxml/test.cpp.hxml

script:
  # Build and run unit tests
  - haxe hxml/test.neko.hxml
  - haxe hxml/test.cpp.hxml
  - haxe hxml/test.js.hxml
  - neko out/neko/test.n
  - ./out/cpp/TestAll-debug

  # Check if app builds
  - haxe hxml/app.neko.hxml
  - haxe hxml/app.cpp.hxml
